# Generated by Django 4.2.13 on 2026-04-05 00:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('farm_owner', 'Farm Owner'), ('regulator', 'Regulator'), ('consumer', 'Consumer')], default='consumer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('species', models.CharField(choices=[('chicken', 'Chicken'), ('goat', 'Goat'), ('cattle', 'Cattle'), ('pig', 'Pig')], max_length=20)),
                ('count', models.PositiveIntegerField()),
                ('arrival_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('processed', 'Processed'), ('quarantine', 'Quarantine')], default='active', max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fssai_license', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('farm', 'Farm'), ('slaughterhouse', 'Slaughterhouse')], default='farm', max_length=20)),
                ('state', models.CharField(default='Maharashtra', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('animal_capacity', models.PositiveIntegerField(default=500)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('warning', 'Warning'), ('non_compliant', 'Non-Compliant')], default='compliant', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waste_type', models.CharField(choices=[('solid', 'Solid Organic'), ('liquid', 'Liquid Effluent'), ('blood', 'Blood'), ('chemical', 'Chemical')], max_length=20)),
                ('quantity_kg', models.FloatField()),
                ('disposal_method', models.CharField(choices=[('biogas', 'Biogas Plant'), ('composting', 'Composting'), ('sewer', 'Municipal Sewer'), ('untreated', 'Untreated Discharge'), ('third_party', 'Third-Party Handler')], max_length=20)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='butcher_grid.facility')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('medication_type', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('hormone', 'Hormone'), ('vaccine', 'Vaccine')], max_length=20)),
                ('dosage_mg', models.FloatField()),
                ('withdrawal_period_days', models.PositiveIntegerField(default=0)),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='butcher_grid.animalbatch')),
            ],
        ),
        migrations.AddField(
            model_name='animalbatch',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='butcher_grid.facility'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('antibiotic_overuse', 'Antibiotic Overuse'), ('hormone_flag', 'Hormone Flag'), ('waste_anomaly', 'Waste Anomaly'), ('compliance_breach', 'Compliance Breach')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='butcher_grid.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
